Repository TheAlgorithms/TypeScript, pull requests merged in 2022-10, with the labels that each got.

#32 Algorithm: Binary Search
  Search/BinarySearch.ts
  Search/test/BinarySearch.test.ts
Labels: enhancement

#30 algorithm: average/mean
  Maths/calculateMean.ts
  Maths/test/calculateMean.test.ts
Labels: enhancement

#58 chore: update codeowners
  .github/CODEOWNERS
Labels: enhancement, invalid

#65 chore: fix spelling typo
  Sorts/InsertionSort.ts
Labels: bug

#60 algorithm: aliquot sum
  Maths/AliquotSum.ts
  Maths/test/AliquotSum.test.ts
Labels: enhancement

#59 Fix guide on writing good tests
  CONTRIBUTING.md
Labels: documentation

#67 Adding new bug issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation

#77 docs: update filename guidelines
  CONTRIBUTING.md
  DIRECTORY.md
  maths/lowest_common_multiple.ts
  maths/test/lowest_common_multiple.test.ts
  search/linear_search.ts
  search/test/linear_search.test.ts
Labels: enhancement
